[package]
name = "sound_cows"
version = "0.1.0"
edition = "2024"

[dependencies]
ratatui = "0.30.0"
crossterm = "0.29"
rodio = "0.20"
anyhow = "1.0"
symphonia = { version = "0.5.3", features = ["mp3", "pcm"] }
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
