[package]
name = "sound_cows"
version = "0.1.0"
edition = "2024"

[dependencies]
ratatui = "0.30.0"
crossterm = "0.29"
rodio = "0.21.1"
duckdb = { version = "1.1.1", features = ["bundled"] }
anyhow = "1.0.100"
serde = "1.0.228"
serde_derive = "1.0.228"
serde_json = "1.0.149"
